### ISSUE TITLE
How to use premium skynet account ?

### ISSUE THREAD

**Issue by dionaditya** [Fluffy9/Zenbase#3]

**Comment by Fluffy9** [comment]
I didn't implement it and I'm not too sure it would be a good idea. 

1. Skynet seems to already keep content hosted for quite a while for free, plus GunDB will write to it frequently which keeps it fresh. 
2. Performance wise doesn't matter. GunDB should pull from peers (and localstorage) before it pulls from Skynet. 
3. If you need a lot of storage space, you're probably doing something wrong. Don't save images in GunDB directly, save them to your premium account perhaps and then save the link in GunDB
4. You probably wouldn't want anyone and everyone using your p2p project having full control over your account
