### ISSUE TITLE
Help!!!! zenbase-2.1.6 is defect, get NO data, but ERRORS!!!!

### ISSUE THREAD

**Issue by parajbs** [Fluffy9/Zenbase#5]
**Hello Fluffy9,**

I tested everything with the original code, even with different browsers, but I always got errors! 
But I already found a solution!

########
1. Here is my **test1** (original zenbase-2.1.6 / debug=true) link:
https://jsfiddle.net/dvhs15wp/1/

**Test1 errors**:
a) list File '' does not have root radix!
b) Error: Expected parameter 'json' to be type 'object', was type 'string', value '{"!":{"":1}}' at throwValidationError (https://skynet-js.hns.siasky.net/4.0-beta/index.js:15552:11) at Object.validateObject 
c) Uncaught SyntaxError: redeclaration of var Gun

########
2. Here my **Test2** (Original zenbase-2.1.6 / debug=true / without the gun.put command!) Link:
https://jsfiddle.net/dvhs15wp/2/

Test2 errors:
a) list File '' does not have root radix!
b) Error: Expected parameter 'json' to be type 'object', was type 'string', value '{"!":{"":1}}' at throwValidationError (https://skynet-js.hns.siasky.net/4.0-beta/index.js:15552:11) at Object.validateObject 
c) Uncaught SyntaxError: redeclaration of var Gun

########
_**!!!Warning!!!** If you change the secret, there will be four 404 GET_Errors on the first run, but all further runs are then OK!!!_

3. Here is my **Test3** (my patched zenbase-2.1.6-patch1b / debug=true) link:
https://jsfiddle.net/dvhs15wp/3/

No errors, everything OK and data!

###########
4. Here my **Test4** (my patched zenbase-2.1.6-patch1b / debug=true / without the gun.put command!) Link:
https://jsfiddle.net/dvhs15wp/4/

No errors, everything OK and data!

_**!!!Very important for testing Zenbase!!!**
To test if everything is OK, you have to comment out the "gun.put" command and then see if the data can also be loaded without first executing the "gun.put" command!!!_

Here is the link to my new zenbase-2.1.6-patch1b :
https://4001kpf6rhpvb1694id2alaoa0kua26bkdspj68jejgelahsdankfno.siasky.net/zenbase/index_2_1_6_patch1b.js

Have fun testing!
With friendly greetings
**parajbs**

**Comment by Fluffy9** [comment]
I'm not sure what was causing the issue but 2.1.7 seems to work with your changes. Thanks

**Comment by parajbs** [comment]
Hello Fluffy9,

Yesterday I installed "SkynetLabs/gundb-relay(branch "skynet-nodejs")" on my dev server and fixed errors while doing so
I have now created a super working new version of "zenbase-2.1.8_2-beta-plus" that works both in the browser and in nodejs!
But I think there is still a problem with the gun in the relay!
 
I haven't published the version "zenbase-2.1.8_2-beta-plus" on github yet because I also use "SkynetLabs/nodejs-skynet" and there in the "src/client.js" the line:

      getJSON: browserClient.db.getJSON.bind(browserClient),

 added so that "getJSON" also works in nodejs!
I'm still waiting for the line to be included in the original repo!
Although I also have a version that works without the correction of "SkynetLabs/nodejs-skynet", but the version is extremely big, and double functions for browser and nodejs!

"SkynetLabs/nodejs-skynet" without correction:
    // SkyDB
    this.db = {
      setDataLink: browserClient.db.setDataLink.bind(browserClient),
    };


"SkynetLabs/nodejs-skynet" with correction:
    // SkyDB
    this.db = {
      setDataLink: browserClient.db.setDataLink.bind(browserClient),
      getJSON: browserClient.db.getJSON.bind(browserClient),
    };

If you want to help with the problems then I'll try to upload both versions of my dev server to my githab repo today or tomorrow!

You can contact the developers of "SkynetLabs/nodejs-skynet" to include this line:
    getJSON: browserClient.db.getJSON.bind(browserClient),
see above!!!
"db.getJSON" can then also be used in the nodejs version!
Danger! IMPORTANT! "setJSON" is not meant because this doesn't work, only "getJSON"! This is why "getJSON" is compatible with skydb data!

- How about a cool WebUI?
- And as an option encryption and decryption of the data by Gun or by skynet (there is no such thing for skydb at the moment!) or
other secure encryption!
- Or user DB, via skynet-mysky or Gun SEC?
